# TCL File Generated by Component Editor 17.0
# Wed Mar 23 14:15:59 IST 2022
# DO NOT MODIFY


# 
# DMA "DMA" v1.0
#  2022.03.23.14:15:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DMA
# 
set_module_property DESCRIPTION ""
set_module_property NAME DMA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DMA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DMA
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DMA.vhd VHDL PATH DMA.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter Data_Width INTEGER 32
set_parameter_property Data_Width DEFAULT_VALUE 32
set_parameter_property Data_Width DISPLAY_NAME Data_Width
set_parameter_property Data_Width TYPE INTEGER
set_parameter_property Data_Width UNITS None
set_parameter_property Data_Width HDL_PARAMETER true
add_parameter Address_Width INTEGER 32
set_parameter_property Address_Width DEFAULT_VALUE 32
set_parameter_property Address_Width DISPLAY_NAME Address_Width
set_parameter_property Address_Width TYPE INTEGER
set_parameter_property Address_Width UNITS None
set_parameter_property Address_Width HDL_PARAMETER true
add_parameter hps_address_base STD_LOGIC_VECTOR 4294901760
set_parameter_property hps_address_base DEFAULT_VALUE 4294901760
set_parameter_property hps_address_base DISPLAY_NAME hps_address_base
set_parameter_property hps_address_base TYPE STD_LOGIC_VECTOR
set_parameter_property hps_address_base UNITS None
set_parameter_property hps_address_base ALLOWED_RANGES 0:4294967295
set_parameter_property hps_address_base HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point sink
# 
add_interface sink reset end
set_interface_property sink associatedClock clock
set_interface_property sink synchronousEdges DEASSERT
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink rsi_sink_reset_n reset_n Input 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset sink
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master avm_master_read read Output 1
add_interface_port master avm_master_address address Output address_width
add_interface_port master avm_master_readdata readdata Input data_width
add_interface_port master avm_master_waitrequest waitrequest Input 1
add_interface_port master avm_master_readdatavalid readdatavalid Input 1


# 
# connection point mastertohps
# 
add_interface mastertohps avalon start
set_interface_property mastertohps addressUnits SYMBOLS
set_interface_property mastertohps associatedClock clock
set_interface_property mastertohps associatedReset sink
set_interface_property mastertohps bitsPerSymbol 8
set_interface_property mastertohps burstOnBurstBoundariesOnly false
set_interface_property mastertohps burstcountUnits WORDS
set_interface_property mastertohps doStreamReads false
set_interface_property mastertohps doStreamWrites false
set_interface_property mastertohps holdTime 0
set_interface_property mastertohps linewrapBursts false
set_interface_property mastertohps maximumPendingReadTransactions 0
set_interface_property mastertohps maximumPendingWriteTransactions 0
set_interface_property mastertohps readLatency 0
set_interface_property mastertohps readWaitTime 1
set_interface_property mastertohps setupTime 0
set_interface_property mastertohps timingUnits Cycles
set_interface_property mastertohps writeWaitTime 0
set_interface_property mastertohps ENABLED true
set_interface_property mastertohps EXPORT_OF ""
set_interface_property mastertohps PORT_NAME_MAP ""
set_interface_property mastertohps CMSIS_SVD_VARIABLES ""
set_interface_property mastertohps SVD_ADDRESS_GROUP ""

add_interface_port mastertohps avm_mastertohps_write write Output 1
add_interface_port mastertohps avm_mastertohps_address address Output address_width
add_interface_port mastertohps avm_mastertohps_writedata writedata Output data_width
add_interface_port mastertohps avm_mastertohps_waitrequest waitrequest Input 1


# 
# connection point i_controll
# 
add_interface i_controll conduit end
set_interface_property i_controll associatedClock clock
set_interface_property i_controll associatedReset sink
set_interface_property i_controll ENABLED true
set_interface_property i_controll EXPORT_OF ""
set_interface_property i_controll PORT_NAME_MAP ""
set_interface_property i_controll CMSIS_SVD_VARIABLES ""
set_interface_property i_controll SVD_ADDRESS_GROUP ""

add_interface_port i_controll i_control_startaddress startaddress Input address_width
add_interface_port i_controll i_control_stopaddress stopaddress Input address_width

