# TCL File Generated by Component Editor 17.0
# Sun May 01 13:18:39 IDT 2022
# DO NOT MODIFY


# 
# Master_Memory "Master_Memory" v1.0
#  2022.05.01.13:18:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Master_Memory
# 
set_module_property DESCRIPTION ""
set_module_property NAME Master_Memory
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Master_Memory
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Master_Memory
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Master_Memory.vhd VHDL PATH Master_Memory.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter Data_Width INTEGER 32
set_parameter_property Data_Width DEFAULT_VALUE 32
set_parameter_property Data_Width DISPLAY_NAME Data_Width
set_parameter_property Data_Width TYPE INTEGER
set_parameter_property Data_Width UNITS None
set_parameter_property Data_Width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property Data_Width HDL_PARAMETER true
add_parameter Address_Width INTEGER 10
set_parameter_property Address_Width DEFAULT_VALUE 10
set_parameter_property Address_Width DISPLAY_NAME Address_Width
set_parameter_property Address_Width TYPE INTEGER
set_parameter_property Address_Width UNITS None
set_parameter_property Address_Width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property Address_Width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point sink
# 
add_interface sink reset end
set_interface_property sink associatedClock clock
set_interface_property sink synchronousEdges DEASSERT
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink rsi_sink_reset_n reset_n Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset sink
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source aso_source_Data data Output data_width
add_interface_port source aso_source_valid valid Output 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits WORDS
set_interface_property master associatedClock clock
set_interface_property master associatedReset sink
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master avm_master_read read Output 1
add_interface_port master avm_master_write write Output 1
add_interface_port master avm_master_address address Output address_width
add_interface_port master avm_master_readdata readdata Input data_width
add_interface_port master avm_master_writedata writedata Output data_width
add_interface_port master avm_master_waitrequest waitrequest Input 1
add_interface_port master avm_master_readdatavalid readdatavalid Input 1


# 
# connection point i_control
# 
add_interface i_control conduit end
set_interface_property i_control associatedClock clock
set_interface_property i_control associatedReset sink
set_interface_property i_control ENABLED true
set_interface_property i_control EXPORT_OF ""
set_interface_property i_control PORT_NAME_MAP ""
set_interface_property i_control CMSIS_SVD_VARIABLES ""
set_interface_property i_control SVD_ADDRESS_GROUP ""

add_interface_port i_control i_control_read read Input 1
add_interface_port i_control i_control_write write Input 1
add_interface_port i_control i_control_startaddress startaddress Input address_width
add_interface_port i_control i_control_stopaddress stopaddress Input address_width


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 1
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink asi_sink_writedata data Input data_width+address_width
add_interface_port avalon_streaming_sink asi_sink_ready ready Output 1


# 
# connection point dataaddress_out
# 
add_interface dataaddress_out conduit end
set_interface_property dataaddress_out associatedClock clock
set_interface_property dataaddress_out associatedReset ""
set_interface_property dataaddress_out ENABLED true
set_interface_property dataaddress_out EXPORT_OF ""
set_interface_property dataaddress_out PORT_NAME_MAP ""
set_interface_property dataaddress_out CMSIS_SVD_VARIABLES ""
set_interface_property dataaddress_out SVD_ADDRESS_GROUP ""

add_interface_port dataaddress_out aso_source_dataaddress startofpacket Output address_width

